name: turo_app
description: "A new Flutter project for a mentor-mentee app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo_white.svg
    - lib/assets/images/Sign Up - Mentee.svg
    - lib/assets/images/Sign Up - Mentee2.svg
    - lib/assets/images/Sign Up - Mentee3.svg
    - lib/assets/images/Sign Up - Mentee4.svg

  fonts:
    - family: Fustat
      fonts:
        - asset: lib/assets/fonts/FustatRegular.ttf
          weight: 400
        - asset: lib/assets/fonts/FustatSemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/FustatExtraBold.ttf
          weight: 800
